version: '3'

volumes:
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge

services:
  nginx:
    env_file:
       - .env
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
      args:
        DOMAIN: ${DOMAIN}
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      #- ./requirements/nginx/public:/var/www/public
      - ./requirements/nginx/cert:/etc/nginx/cert
      - wp-volume:/var/www/
    restart: unless-stopped

  mariadb:
    env_file:
       - .env  
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PASS: ${DB_USER_PASS}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    env_file:
       - .env
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PASS: ${DB_USER_PASS}
        WP_TITLE: ${WP_TITLE}
        WP_ADMIN: ${WP_ADMIN}
        WP_ADMIN_PASS: ${WP_ADMIN_PASS}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_USER: ${WP_USER}
        WP_USER_PASS: ${WP_USER_PASS}
        WP_USER_EMAIL: ${WP_USER_EMAIL}
    container_name: wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: unless-stopped

