version: '3'

services:
  nginx:
    env_file:
       - .env
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
      args:
        DOMAIN: ${DOMAIN}
    container_name: nginx
#    depends_on:
#      - wordpress
    ports:
      - "443:443"
#    networks:
#      - inception
    volumes:
      - ./requirements/nginx/public:/var/www/public
#      - wp-volume:/var/www/
      - ./requirements/nginx/cert:/etc/nginx/cert
    restart: always
